### ISSUE TITLE
Playnext as buffer

### ISSUE THREAD

**Issue by ConnorFoody** [me-next/menext-backend#57]
@daniel-centore  do we want to have an option for the play-next queue to act as a buffer? Should that be default?

**Comment by daniel-centore** [comment]
What do you mean by that?

**Comment by ConnorFoody** [comment]
I think we talked a little about having the next few songs to play always in the play-next queue (pnq). 

It would look like: 
1. Song is playing, 2 songs in the pnq, a bunch in the suggestion queue
2. Song finishes
3. Next song is pulled from the pnq. The pnq has 1 song
4. A song is removed from the suggestion queue and put into the pnq, so pnq is back at 2 songs
5. Request returns, change is registered

steps 2-4 all happen "in" the same change

**Comment by daniel-centore** [comment]
I think one of us may have misunderstood the other. What I believe you're referencing (as I understood it) was the user scenario where the host decides to always have a song or two in play next which he/she adds manually, so he/she always has control over which songs play. However, if the host chooses not to do this, then it just auto picks from the suggestion queue, since nothing is in play next.

**Edit:** I'm not sure I see any advantage to doing it as your propose. Is there one I'm overlooking?

**Comment by ConnorFoody** [comment]
ok, sounds good.
